version: '3.9'

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=cowhub
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=popolilo
        ports:
            - 5432:5432
        volumes:
            - ./../system/data/cowhub:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
        - PGADMIN_DEFAULT_EMAIL=admin@mail.com
        - PGADMIN_DEFAULT_PASSWORD=root
        ports:
        - 5050:80

